# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventTime', models.DateTimeField()),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventStatus', models.CharField(choices=[(b'ONGOING', b'Ongoing'), (b'COMPLETED', b'Completed'), (b'GOING_TO_START', b'Going to start'), (b'IDLE', b'Idle')], default=b'IDLE', max_length=100)),
                ('eventDescription', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('eventTime',),
            },
        ),
    ]
