# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_status', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
    ]
