# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.CharField(default=b'Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(default=b'Not Available', max_length=100),
        ),
    ]
