# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_auto_20160910_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stall',
            options={'ordering': ('stallId',)},
        ),
        migrations.RemoveField(
            model_name='stall',
            name='id',
        ),
        migrations.AddField(
            model_name='stall',
            name='stallId',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stall',
            name='slug',
            field=models.SlugField(default=b'-1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallDescription',
            field=models.CharField(default=b'Not Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallLocation',
            field=models.CharField(default=b'Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallName',
            field=models.CharField(default=b'Not Available', max_length=100),
        ),
    ]
