# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0003_auto_20160910_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
