# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0006_remove_stall_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='stallLocation',
        ),
    ]
