# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0007_remove_stall_stalllocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stallLocation',
            field=models.CharField(default=b'Not Available', max_length=100),
        ),
    ]
