# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0008_stall_stalllocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
