# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0009_auto_20160912_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='id',
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
