# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0010_auto_20160912_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallDescription',
            field=models.CharField(default='Not Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallLocation',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stallName',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
